# Site identity
# (Displays in browser tab and header)
title: Aurelius V1
description: A personal dashboard to orient my life
baseurl: ""
url: "https://mithellfgibson.github.io"

# Use Just the Docs as a remote theme
remote_theme: just-the-docs/just-the-docs

# Manual sidebar: only three items
nav:
  - title: "Balanced"
    url: "/"

  - title: "To-Do"
    children:
      - title: "List"
        url: "/todo"

  - title: "Calendar"
    children:
      - title: "View"
        url: "/calendar"

# Custom CSS overrides
just_the_docs:
  custom_css:
    - assets/css/custom.css

# Default permalink style
permalink: pretty

# Ensure all pages use default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude all non-relevant files and folders
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - CHANGELOG.md
  - MIGRATION.md
  - CODE_OF_CONDUCT.md
  - fixtures/
  - docs/
  - components/
  - utilities/
  - navigation/
  - layout/
  - assets/js/
  - assets/css/just-the-docs*.css

# Configure search (optional)
search_enabled: false

# Optional: disable default GitHub attribution
aux_links: {}

# Footer & misc features
back_to_top: true
gh_edit_link: false
heading_anchors: true
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
